Deactivate webserver12
IATI/deployment pull request #39
Opened 2018-06-18 12:27 UTC by allthatilk

Comment out webserver 12 from `servers.ini` and add note as to why.

2018-06-19 16:39 UTC, akmiller01 approved these changes

2018-06-20 14:00 UTC, dalepotter commented
Suggest deleting this rather than commenting out.

2018-06-21 09:11 UTC, dalepotter requested changes
As above

2018-07-31 15:40 UTC, dalepotter approved these changes

2018-07-31 15:42 UTC, dalepotter commented
Approved changes! Just to note for posterity here, that `webserver12` was a small utility server which was only ever used for ad-hoc small jobs at one time. It was first set-up in April 2015 and was decommissioned in April 2018.

2018-07-31 15:43 UTC, merged